#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=32
#PBS -N 2018_new_core_diversity_analyses
#PBS -A d411-training
#PBS -j oe
cd $PBS_O_WORKDIR
module load miniconda/python2
# loading virtualenv
echo "loading virtualenv"
#setting temp directory 
export TMPDIR=~/qiime_tmp
# NB qiime1 and not qiimel (number one not letter l)
source activate qiime1
#diversity analysis
echo "diversity analysis"
core_diversity_analyses.py -o Cnb_CDA -i ~/cannabis/BIOM_Table/filtered2_otu_table.biom -m ~/cannabis/mapping_files/MERGE/merged_mapping.txt -e 3600 -t ~/2018_02_smb/otus18/97_otus.tree -a -O 16
#deactivate emv
source deactivate
